language: node_js

node_js: 10

script: |
  ./node_modules/.bin/vsce package

before_deploy: |
  export TRAVIS_TAG="published/$(jq -j '.version' < package.json)"

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: release
  script: bash ./deploy.sh
