language: node_js

node_js: 10

script: |
  ./node_modules/.bin/vsce package

before_deploy: |
  export TRAVIS_TAG="published/$(jq -j '.version' < package.json)"

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: release
  script: |
    # publish to marketplace
    ./node_modules/.bin/vsce publish -p $VSCE_TOKEN --packagePath *.vsix

    # tag commit
    git tag "${TRAVIS_TAG}"

    # push tag
    git remote add origin-tagging https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    git push origin-tagging "${TRAVIS_TAG}"
