language: node_js

node_js: 10

branches:
  except:
  - /^published\/.*$/

script: |
  ./node_modules/.bin/vsce package

before_deploy: |
  export VERSION="$(jq -j '.version' < ./package.json)"
  export TRAVIS_TAG="published/${VERSION}"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: release
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    skip_cleanup: true
    name: "Alan for Visual Studio Code v${VERSION}"
    on:
      branch: release
